searcher:
  version: 1.x
  js:
    js/react.min.js: {}
    js/react-dom.min.js: {}
    js/browser.min.js: {}
    js/product_search.js: {}
    js/transformed/searcher.js: {}
  dependencies:
      - core/jquery

awesomplete:
  version: 1.x
  js:
    awesomplete/awesomplete.js: {}
  css:
    component:
      awesomplete/awesomplete.css: {}
