<?php

/**
 * @file
 * Contains product_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function product_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the product_search module.
    case 'help.page.product_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A simple products searcher') . '</p>';
      return $output;

    default:
  }
}

/**
 *  Implements hook_page_attachments().
 */
function product_search_page_attachments(array &$page) {
  /*$description = [
    '#tag' => 'meta',
    '#attributes' => [
      'name' => 'description',
      'content' => t('Searcher of products and services'),
    ],
  ];
  $keywords = [
    '#tag' => 'meta',
    '#attributes' => [
      'name' => 'keywords',
      'content' => t('Products, services in general. Like garden services, mason, colourman, secreatary, doctor, computing, companies, etc'),
    ],
  ];

  $page['#attached']['html_head'][] = [
    $description,
    'description',
  ];

  $page['#attached']['html_head'][] = [
    $keywords,
    'keywords',
  ];*/


}

/**
 * Implements hook_theme().
 */
function product_search_theme() {
  $theme = [];

  return $theme;
}
